config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'students#index'
  resources :students, only:[:index, :update, :create, :destroy] do
    collection do 
      get :new_modal
    end 
    member do 
      get :edit_modal
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: %i[update edit_modal destroy]
	def index
		@students = current_user.students.paginate(page: params[:page], per_page: 10).order('updated_at desc')
	end

	def create
		if student_params[:name].present? && student_params[:subject].present?
			name 		= student_params[:name].downcase
			subject = student_params[:subject].downcase
			mark 		= student_params[:mark]
			@student = Student.find_by(name: name, subject: subject, user_id: current_user.id)
			if @student.present? && @student.update(mark: mark)
				flash[:warning] = 'Student With Same Subject Already Exists Updated The Mark'
				redirect_to students_path
			else
				@student = Student.new(lower_student_params.merge({user_id: current_user.id}))
				if @student.save
					flash[:success] = 'Student Added Successfully'
					redirect_to students_path
				end
			end
		else 
			flash[:error]= 'Error Adding User'
			redirect_to students_path
		end
	end

	def lower_student_params
		student_params.transform_values do |value|
		  value.is_a?(String) ? value.downcase : value
		end
	end


	def edit_modal
		@student = Student.find(params[:id])
		render 'edit_modal.js', layout: false
	end

	def new_modal
		render 'new_modal.js', layout: false
	end

	def update
		
		if @student.update(lower_student_params)
			flash[:success] = 'Student Updated Successfully'
			redirect_to students_path
		end
	end

	def destroy
		if @student.destroy
			flash[:danger] = 'Student Deleted'
			redirect_to students_path
		end
	end

	private

	def student_params
		params.require(:student).permit(:name, :subject, :mark)
	end

	def set_student
		@student = Student.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="<%students_path%>">Teacher Portal</a>
        <%if current_user.present?%>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-brand" %>
        <%end%> 
      </nav>
      <br>

      <%notice = notice == alert ? nil : notice%>
      <%= render partial: 'shared/flash_message'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key == 'error' ? 'danger' : key %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/students/_edit_modal.html.erb
<div class="modal", id="mymodal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%=form_for :student, url: student_path(@student), method: :put do |f|%>
          <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Student Name', required: true, value: @student.name.titleize%>
          </div>
          <div class="form-group">
            <%= f.text_field :subject, class: 'form-control', placeholder: 'Subject', required: true, value: @student.subject.titleize%>
          </div>
          <div class="form-group">
            <%= f.number_field :mark, class: 'form-control', placeholder: 'Mark', min: 0, required: true%>
          </div>
          <div class="form-group">
            <%= f.submit 'submit', class: 'btn btn-primary', style: 'float: right;'%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/students/_new_modal.html.erb
<div class="modal", id="mymodal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%=form_for :student, url: students_path do |f|%>
          <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Student Name', required: true%>
          </div>
          <div class="form-group">
            <%= f.text_field :subject, class: 'form-control', placeholder: 'Subject', required: true%>
          </div>
          <div class="form-group">
            <%= f.number_field :mark, class: 'form-control', placeholder: 'Mark', min: 0, required: true%>
          </div>
          <div class="form-group">
            <%= f.submit 'submit', class: 'btn btn-primary', style: 'float: right;'%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/students/edit_modal.js.erb
$(document).ready(function (argument) {
  $('#modal').html("<%= j render(partial: 'edit_modal')%>")

  $(".modal").modal('show')
});

app/views/students/index.html.erb
<div id="modal"></div>
<%= link_to 'New Student', new_modal_students_path(format: :js), class:"btn btn-success", style:"float: right;margin-bottom: 3px;", type: :button, remote: true %>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Subject</th>
      <th scope="col">Mark</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%@students.each do |student|%>
      <tr>
        <td><%=student.name.titleize%></td>
        <td><%=student.subject.titleize%></td>
        <td><%=student.mark%></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-secondary btn-sm  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              :
            </button>
            <div class="dropdown-menu">
            
              <%= link_to 'Edit', edit_modal_student_path(id: student.id, format: :js), class:"dropdown-item", remote: true %>
              <%= link_to 'Delete', student_path(student), class: 'dropdown-item', method: :delete %>
            </div>
          </div>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

<%= will_paginate @students, renderer: BootstrapPagination::Rails %>

app/views/students/new_modal.js.erb
$(document).ready(function (argument) {
  $('#modal').html("<%= j render(partial: 'new_modal')%>")

  $(".modal").modal('show')
});